### ISSUE TITLE
TypeError: Cannot read property 'compile' of undefined

### ISSUE THREAD

**Issue by yonguilee** [yonguilee/fivepieces#1]
Operating System: Windows 10
Node Version: v10.13.0
NPM Version: 6.4.1
webpack Version: 3.6.0
webpack-dev-server Version: 3.1.10

**Expected Behavior**
I expect to be able to run the webpack-dev-server.

**Actual Behavior**
When attempting to run the webpack-dev-server, an error is being thrown:

```
C:\Users\ye243\five\five>npm run dev

> five@1.0.0 dev C:\Users\ye243\five\five
> webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

TypeError: Cannot destructure property `compile` of 'undefined' or 'null'.
    at addHooks (C:\Users\ye243\five\five\node_modules\webpack-dev-server\lib\Server.js:114:49)
    at new Server (C:\Users\ye243\five\five\node_modules\webpack-dev-server\lib\Server.js:127:5)
    at startDevServer (C:\Users\ye243\five\five\node_modules\webpack-dev-server\bin\webpack-dev-server.js:355:14)
    at processOptions (C:\Users\ye243\five\five\node_modules\webpack-dev-server\bin\webpack-dev-server.js:309:5)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
```

**Comment by yonguilee** [comment]
I think it happened after installing webpack 4 globally for my another project..
